:icons: font
:toc:
:source-language: console

ifdef::env-github,env-browser[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Enable Serial/SOL Output for RHEL, CentOS, or Fedora
lxvs
2.0, 2026/8/19

[#permanently]
== Permanently

Use the following command to permanently enable serial output (effective on next boot):

----
sudo grubby --update-kernel=ALL --args="console=ttyS0,115200 console=tty0"
----

See more about `console` parameter on https://docs.kernel.org/admin-guide/serial-console.html[kernel documents^].  If anything unexpected happens, see <<recovery,the recovery section>>.

[#temporarily]
== Temporarily

. When the system boots to grub menu, press `e` to edit boot options.
. In the line starting with `linux`, append `console=ttyS0,115200
  console=tty0` to the end.
. Press `Ctrl + x` to continue to boot.

[#recovery]
== Recovery

For _temporarily_, the changes will be restored after a system reboot. For
_permanently_, do the opposite of <<temporarily,_temporarily_>> (instead of
appending console parameters, remove them). After booting successfully into the OS, use the following command to remove previously appended parameters:

----
sudo grubby --update-kernel=ALL --remove-args="console=ttyS0,115200 console=tty0"
----

---

link:#[Back to Top] | link:/[Home]
