= Docs

== Python Projects

[#jsa]
jsa (https://github.com/lxvs/jsa[GitHub^])::
A wrapper of ipmitool, The name `jsa` is just a random word that isn't an existing command.

[#rimesync]
rimesync (https://github.com/lxvs/rimesync[GitHub^])::
Auto deploy or syncing userdb for https://rime.im/[Rime^].

[#runmru]
runmru (https://github.com/lxvs/runmru[GitHub^])::
Delete specific items from Windows runmru.

== Shell Scripts

jg (https://github.com/lxvs/jg[GitHub^])::
A bunch of utilities for git daily use.  Like <<jsa, jsa>>, `jg` is also a random word.

jenkinsbuild (https://github.com/lxvs/jenkinsbuild[GitHub^])::
Setup git daemon and build Jenkins with a single command.

[#open-with-neovim]
open-with-neovim (https://github.com/lxvs/open-with-neovim[GitHub^])::
Show item [*Open with https://neovim.io/[NeoVim^]*] to all files, and register associations for common file types.
Windows only, use it in Git Bash or Cygwin.

opal (https://github.com/lxvs/opal[GitHub^])::
A simple shell script driving https://github.com/Drive-Trust-Alliance/sedutil[sedutil-cli^].

vom (Vim on Mintty) ^[Deprecated]^ (https://github.com/lxvs/vom[GitHub^])::
It turns out, in Windows, the Vim coming with Git for Windows is more convenient than gVim.  This shell
script makes that Vim the default editor, associates common file types to it, and add an *Edit with Vim on
Mintty* item to right-click menu of files.  Now that I migrated to https://neovim.io/[NeoVim^], it's deprecated
in favor of <<open-with-neovim, open-with-neovim>>.

a2 ^[Deprecated]^ (https://github.com/lxvs/a2[GitHub^])::
A simple shell script to control aria2c.  Do not use it; write a systemd service instead.

== Batch Scripts

[#winchecksumwrapper]
Winchecksum Wrapper (https://github.com/lxvs/winchecksumwrapper[GitHub^])::
A wrapper of <<winchecksum, winchecksum>>, adding winchecksum commands to right-click menu of files.

[#winchecksum]
Winchecksum (https://github.com/lxvs/winchecksum[GitHub^])::
A wrapper of `certutil.exe` to calculate checksums of a file.

jai (Just Archive It) (https://github.com/lxvs/jai[GitHub^])::
A batch script to compress directories to 7z archives (by adding items to right-click menu of directories).

Steam Account Switcher (https://github.com/lxvs/steamaccountswitcher[GitHub^])::
Switch Steam account without re-entering passwords.

copyappdata (https://github.com/lxvs/copyappdata[GitHub^])::
Copy certain portion of AppData from one Windows user to another.

tvren ^[Deprecated]^ (https://github.com/lxvs/tvren[GitHub^])::
A batch script to rename files or directories.  It does not support regex.  Can be seen as a wrapper of `ren`
command.  For regex batch renaming tool on Windows, you may want to check out
https://www.ghisler.com/[Total Commander^].  Regex renaming is just one tiny piece of its features.

runmru-bat ^[Deprecated]^ (https://github.com/lxvs/runmru-bat[GitHub^])::
Delete specific items from Windows runmru.
It has been deprecated in favor of <<runmru, runmru>> (Python implementation).

ipmi ^[Deprecated]^ (https://github.com/lxvs/ipmi[GitHub^])::
A batch script to make ipmitool more handy.  It was retired on November 3rd, 2021, superseded by <<jsa, jsa>> 
(Python implementation with more features).

link:/docs/checksum[checksum] ^[Deprecated]^ (https://github.com/lxvs/checksum[GitHub^])::
A batch script adding checksum calculation to Windows right-click menus.  It has retired and been superseded
by <<winchecksumwrapper, Winchecksum Wrapper>>.

cscratch ^[Deprecated]^ (https://github.com/lxvs/cscratch[GitHub^])::
A simple batch script to setup Visual Studio Build Environment, and provide some simple shortcut commands.
Do not use it; get a GNU/Linux VPS/VM/WSL and use gcc instead.

link:/docs/cloudconf[cloudconf] ^[Deprecated]^ (https://github.com/lxvs/cloudconf[GitHub^])::
A batch script for syncing configurations from cloud storage for tools like https://www.vim.org/[Vim^],
https://rime.im/[Rime^], https://www.voidtools.com/[Everything^] and
https://www.sumatrapdfreader.org/free-pdf-reader[SumatraPDF^].  For Rime, check out <<rimesync, rimesync>>.

cloudsave ^[Deprecated]^ (https://github.com/lxvs/cloudsave[GitHub^])::
Link local game save files to cloud storage services, such as OneDrive, Dropbox, or Google Drive.  Retired
because I don't go to cybercafes any more.
