= Enable Serial/SOL Output in GNU/Linux Systems

[#temporarily]
== Temporarily

. When system boot to grub menu, press `e` to edit boot options.
. In the line starting with `linux`, append `console=ttyS0,115200n8
  console=tty0` to the end.
. Press `Ctrl + x` to continue to boot.

TIP: The parameters added will be explained in <<parameters, later sections>>.

[#permanently]
== Permanently

[IMPORTANT]
====
Below steps FAILED to pass tests on RHEL 9.3, even though it works on RHEL 8.3
and 9.0. Always test <<temporarily, temporarily>> before continue.

Should anything unexpected happen, see <<recovery, Recovery>>.
====

. Enter directory `/etc/default` and make a backup of file `grub`.
+
[,console]
----
cd /etc/default
sudo cp grub grub.bak
----
. Edit file `/etc/default/grub`, in line starting with `GRUB_CMDLINE_LINUX=`,
  append `console=ttyS0,115200n8 console=tty0` within the quotation marks.
. Execute below commands (the path in the second command may be different,
  depending on the Linux distribution):
+
[,console]
----
sudo grub2-editenv - unset kernelopts
sudo grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
----

TIP: The commands used will be explained in <<commands, later sections>>.

== GRUB Parameters and Commands

[#parameters]
=== GRUB Parameters

In above steps, we added 2 parts to grub options, `console=ttyS0,115200n8` and
`console=tty0`. The former is to direct the console output to the first serial
port (`ttyS0`) at a baud rate of *115200*, with **n**o parity, and *8* data
bits. While the latter part is to specify the system's main display. `tty0`
typically refers to the current virtual terminal on a standard monitor attached
to the machine. 

The `console` being specified twice is to configure the system to duplicate the
console output, sending it to both the serial port and the main display.

[#commands]
=== Commands

`grub2-editenv - unset kernelopts`::
`grub2-editenv` is a utility to edit the GRUB2 environment block, which is a
small, dedicated area where GRUB2 stores persistent data.  The single dash `-`
means the command is going to operate on the default GRUB environment block
instead of on a file.  `unset kernelopts` is to remove previous configured
kernel parameters.

`grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg`::
`grub2-mkconfig` is a utility to generate a new GRUB2 configuration file.  `-o
/boot/efi/EFI/redhat/grub.cfg` specifies the output file for the new
configuration, which is the typical location for Red Hat or Red Hat-based
systems (like Fedora or CentOS) that use UEFI.

[#recovery]
== Recovery

For _temporarily_, the changes will be restore after a system reboot. For
_permanently_, do an opposite of <<temporarily, _temporarily_>> (instead of
appending console parameters, remove them). After booting successfully to OS,
restore `/etc/default/grub` from the backup, and redo the step 3 of
<<permanently, _permanently_>>.
